services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com   # ایمیل برای ورود
      PGADMIN_DEFAULT_PASSWORD: admin_password   # رمز عبور برای ورود
    ports:
      - "5050:80" # پورت 5050 روی سیستم شما به پورت 80 کانتینر متصل می‌شود
    volumes:
      - pgadmin_data:/var/lib/pgadmin # برای ذخیره تنظیمات